### PR TITLE
added ability to track identify

### PR DESCRIPTION
**Pull request by patrickotoole**
- added ability to track identity
- updated tests for new event type

### CODE REVIEW

**Comment by patrickotoole** [comment]
@hankim813 Not sure who to ask to get an approval here? Would you be able to help out here again?

**Comment by hankim813** [comment]
Hey @patrickotoole — thanks for the PR. I no longer work on the product side so hopefully someone from the current team can take a look! @jlee9595 @ucarion @Peripheral1994

**Comment by srthurman** [comment]
Hi @patrickotoole - I'm the Engineering Product Manager for our Destinations team. Thanks for reaching out.
We don't currently have a timeline for this update, but I can take a look to see where we can add it to upcoming work. We'll update this thread/PR as work progresses.
Thanks!

**Comment by rjjacobson** [comment]
@srthurman Hey there -- I'm Ron, CEO of Rockerbox. Just saw your message. Appreciate you getting back to us. 

Just for context, we had originally submitted this PR just about 2 months ago to fix a bug that our current implementation has. We're not looking to add any new functionality but just fix the existing integration for our customers.

I know you're busy but if there's anything we can do to help expedite this please let me know. Happy to have our engineers help.

Thanks!
-rj

**Comment by patrickotoole** [comment]
@jlee9595 @ucarion @Peripheral1994 @srthurman Do you have an updated ETA for this? 

If not, were going to ask the client to implement a work around (although our preference and theirs) is to get this solved through segment.

**Review by calvinfo — APPROVED** [review]

**Pull request merged**
